language: node_js
node_js:
- node
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.6.0
- export PATH="$HOME/.yarn/bin:$PATH"
cache:
  yarn: true
script:
- yarn lint
after_success:
  - eval "$(ssh-agent -s)"            # start the ssh agent
  - chmod 600 ./deploy_key.pem.enc    # this key should have push access
  - ssh-add ./deploy_key.pem.enc
  - git remote add deploy ssh://dobby.work/root/deploy/dobby-front
  - git push deploy